### ISSUE TITLE
WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by weasnerb** [joelbinn/angular-phonecat-hybrid#1]
Hello Joel,

I was following your tutorial on migrating an angular.js app to angular on https://joelbinn.gitbooks.io/hybrid-angular-angularjs-application-with-angular/content/ch1-making-the-hybrid.html when I got a warning about loading angular more than once. I double checked that it was not me following the steps incorrectly, as I then followed your tutorial with the phonecat application and came up with the same results.

Any ideas on what is causing and how to fix this?

Thanks,
-Brian

**Comment by weasnerb** [comment]
It seems that angular.js is in both the vendor.js and scripts.js

**Comment by weasnerb** [comment]
Fixed, please look at https://github.com/angular/ngMigration-Forum/issues/10 for solution

**Comment by joelbinn** [comment]
Hi @Weasnerb,

Sorry for being a little bit slow on responding. Been busy with other things. 

Great that you found the solution! I will update the application.

/Joel
